version: '3.8'

services:
  pg:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbt_password
      POSTGRES_DB: dbt_practice
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d dbt_practice']
      interval: 5s
      timeout: 5s
      retries: 5

  dbt:
    build: .
    depends_on:
      pg:
        condition: service_healthy
    environment:
      DBT_HOST: pg
      DBT_PORT: 5432
      DBT_USER: postgres
      DBT_PASSWORD: dbt_password
    volumes:
      - ./dbt_practice:/usr/app/dbt_practice
      - ./profiles.yml:/.dbt/profiles.yml
    ports:
      - '8080:8080'
    user: 1000:1000
    tty: true
